### ISSUE TITLE
use within python script

### ISSUE THREAD

**Issue by ChocoTonic** [agude/wayback-machine-archiver#14]
is there a way to import this into a python script?

**Comment by agude** [comment]
Hi @ChocoTonic!

It depends what you want to do!

If you just want to archive a single URL, you should be able to do this:

```python3
from wayback_machine_archiver.archiver import format_archive_url, format_archive_url
import requests

# Some setup
session = requests.Session()

retries = Retry(
        total=5,
        backoff_factor=args.rate_limit_in_sec,
        status_forcelist=[500, 502, 503, 504],
)

session.mount("https://", HTTPAdapter(max_retries=retries))
session.mount("http://", HTTPAdapter(max_retries=retries))


MY_URL = "http://example.com"

formatted_url = format_archive_url(MY_URL)
call_archiver(formatted_url, rate_limit_wait=5, session=session)
```

Is that what you need? If not, let me know and I can try to help you do it. :-)

**Comment by ChocoTonic** [comment]
thanks!

**Comment by agude** [comment]
Let me know if you have any issues! Happy to help.

**Comment by ChocoTonic** [comment]
I ran into this error:
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url:

`        call_archiver(formatted_url, rate_limit_wait=5, session=s)`

is my rate limit too low?

**Comment by agude** [comment]
Yeah, when I run my own backups I often set it to 60.

Internet Archive rate limits pretty aggressively, and in the past week or two they seem to have ramped it up.

I'm hoping to fix this someday by using their official API, but they haven't gotten back to my email.

**Comment by ReenigneArcher** [comment]
> 
> 
> Hi @ChocoTonic!
> 
> It depends what you want to do!
> 
> If you just want to archive a single URL, you should be able to do this:
> 
> ```python
> from wayback_machine_archiver.archiver import format_archive_url, format_archive_url
> import requests
> 
> # Some setup
> session = requests.Session()
> 
> retries = Retry(
>         total=5,
>         backoff_factor=args.rate_limit_in_sec,
>         status_forcelist=[500, 502, 503, 504],
> )
> 
> session.mount("https://", HTTPAdapter(max_retries=retries))
> session.mount("http://", HTTPAdapter(max_retries=retries))
> 
> 
> MY_URL = "http://example.com"
> 
> # You *COULD* wrap this in a `for` loop to do multiple URLs
> formatted_url = format_archive_url(MY_URL)
> call_archiver(formatted_url, rate_limit_wait=5, session=session)
> ```
> 
> Is that what you need? If not, let me know and I can try to help you do it. :-)

Hi, I am trying to run this in a Plex metadata agent to help preserve pages which may get removed. I'm unable to install modules, but have included the following manually (kept adding ones that the compiler complained about missing):

- wayback_machine_archiver
- requests
- urllib3
- idna
- chardet
- certifi

I get the following error message: "NameError: global name 'Retry' is not defined". Any idea how to fix it?

P.S. Plex will only run python 2.7

**Comment by agude** [comment]
> I get the following error message: "NameError: global name 'Retry' is not defined". Any idea how to fix it?

😬 Sorry, that code was a quick sketch, and it looks like I missed some imports.

You'll need:

```python
from urllib3.util.retry import Retry
```

> P.S. Plex will only run python 2.7

I feel your pain! My Raspberry Pis only support 2.7 right now, so I'm trying to keep Archiver working on it as well!

**Comment by ReenigneArcher** [comment]
> 
> 
> > I get the following error message: "NameError: global name 'Retry' is not defined". Any idea how to fix it?
> 
> 😬 Sorry, that code was a quick sketch, and it looks like I missed some imports.
> 
> You'll need:
> 
> ```python
> from urllib3.util.retry import Retry
> ```
> 
> > P.S. Plex will only run python 2.7
> 
> I feel your pain! My Raspberry Pis only support 2.7 right now, so I'm trying to keep Archiver working on it as well!

Awesome, thanks! And now I'm getting the same error for 'args'

**Comment by ReenigneArcher** [comment]
> 
> 
> > I get the following error message: "NameError: global name 'Retry' is not defined". Any idea how to fix it?
> 
> 😬 Sorry, that code was a quick sketch, and it looks like I missed some imports.
> 
> You'll need:
> 
> ```python
> from urllib3.util.retry import Retry
> ```
> 
> > P.S. Plex will only run python 2.7
> 
> I feel your pain! My Raspberry Pis only support 2.7 right now, so I'm trying to keep Archiver working on it as well!

@agude okay, thank! There were a few more errors to work out. This is my code now which at least compiles.

```
from wayback_machine_archiver.archiver import format_archive_url, call_archiver
import requests
from urllib3.util.retry import Retry
from requests.adapters import HTTPAdapter

def Wayback(url):
    # Some setup
    time = 60
    
    session = requests.Session()

    retries = Retry(
            total=5,
            backoff_factor=time,
            status_forcelist=[500, 502, 503, 504],
    )

    session.mount("https://", HTTPAdapter(max_retries=retries))
    session.mount("http://", HTTPAdapter(max_retries=retries))

    formatted_url = format_archive_url(url)
    Log.Info("common.Wayback() - Attempting to archive url: '%s'" % (url))
    call_archiver(formatted_url, rate_limit_wait=time, session=session)
```

Not sure if it works, or how long it takes for Wayback to perform the archive. I've been checking to see if there's a snapshot but don't see one.

**Comment by agude** [comment]
Glad to hear it! :-)

**Comment by poissonk** [comment]
Hi @agude, thanks for the work on this project. To pursue the question, how will you proceed to use the "--sitemaps" argument within a python script ?
Regards,

**Comment by agude** [comment]
HI @poissonk:

Something like this. I haven't tested it, but let me know if you have a problem and I can help debug.

```python
import requests
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry

from wayback_machine_archiver.archiver import download_remote_sitemap, extract_pages_from_sitemap


def backup_from_sitemap(sitemap_url: str, wait_time_sec=60) -> None:
    # Setup requests session and configure retry interval
    session = requests.Session()

    retries = Retry(
        total=5,  # Number of retries
        backoff_factor=wait_time_sec,  # seconds
        status_forcelist=[500, 502, 503, 504],  # Bad status codes
    )

    session.mount("https://", HTTPAdapter(max_retries=retries))
    session.mount("http://", HTTPAdapter(max_retries=retries))

    # Download and parse sitemaps
    sitemap_xml = download_remote_sitemap(sitemap_url, session=session)

    # Run backup of URLs
    for url in extract_pages_from_sitemap(sitemap_xml):
        formatted_url = format_archive_url(url)
        call_archiver(formatted_url, rate_limit_wait=wait_time_sec, session=session)
```
