### ISSUE TITLE
Similarity to a feature in Wayback Machine extension?

### ISSUE THREAD

**Issue by Melonadev** [agude/wayback-machine-archiver#22]
The Wayback Machine extension [here](https://github.com/internetarchive/wayback-machine-webextension) has a feature called 'Bulk save', and I find it's principle pretty similar to your archiver, the differences being the user interface and live updates. What's more, it works out great! What do you think of this one?

![image](https://user-images.githubusercontent.com/66422959/100963771-175d7500-3562-11eb-8207-193e0862ffe4.png)

**Comment by agude** [comment]
Here is the script they use to save: https://github.com/internetarchive/wayback-machine-webextension/blob/master/webextension/scripts/bulk-save.js

Specifically, they loop over the URLs and call: https://github.com/internetarchive/wayback-machine-webextension/blob/master/webextension/scripts/bulk-save.js#L178-L198

Looks like they might check if the URL is already saved? So it store the most recent version?

Anyway it probably will work great for your use case! It doesn't meet mine, but I'd love to figure out the API their calling so I can steal it. ;-)
